apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.nreplPort }}
      protocol: TCP
      name: nrepl
  selector:
    app: {{ .Chart.Name }}
