---
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'pull'
      - 'gcr.io/${PROJECT_ID}/${REPO_NAME}:master'
    timeout: 100s
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - 'https://github.com/zlosure/${REPO_NAME}.git#${BRANCH_NAME}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}'
      - '--cache-from'
      - 'gcr.io/${PROJECT_ID}/${REPO_NAME}:master'
    timeout: 600s
images:
  - 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}'
